### ISSUE TITLE
Add gracedb ID to overview page

### ISSUE THREAD

**Issue by shreyasahasram08** [growth-astro/growth-too-marshal#25]
This is a minor issue, but Mansi and Varun pointed out that the ability to search for an event based on its ID would be very useful, just the way one can search for a given target by its ID within a program. I could add a pull request doing this; the question is where would be best to display it?  I was thinking:
GRACEID yymmdd hh:mm:ss 
and we could omit the '(N hours ago)' from the front display.  Any thoughts/suggestions?

**Comment by mansikasliwal** [comment]
N hours ago is very important

**Comment by varunbhalerao** [comment]
GRACEID includes yymmdd, so you could skip that part. That way the total length of the string won't increase by much, and you can keep the hh:mm:ss as well as the 'N hours ago'

**Comment by lpsinger** [comment]
I like the search idea. Note that the URL resolution already has a feature where an event ID of the form YYMMDD will automatically redirect to an event if there is a unique match, or to a disambiguation page if there are multiple results.

Also: would be good to search around for an existing autocomplete widget that we could use for the search box. For example, I’ve started using Twitter’s [typeahead.js](https://github.com/twitter/typeahead.js) in some LIGO tools (see [Flask views](https://git.ligo.org/emfollow/gwcelery/blob/master/gwcelery/views.py) and [Jinja template](https://git.ligo.org/emfollow/gwcelery/blob/master/gwcelery/templates/index.jinja2).

**Comment by mcoughlin** [comment]
@shreyasahasram08 is this still relevant? Maybe would be good to rename this issue to something new? Otherwise some of this is already in there right?
