### ISSUE TITLE
Licensing only implicit in setup.py

### ISSUE THREAD

**Issue by stefanv** [growth-astro/growth-too-marshal#28]
I was wondering if the GPL license mentioned in the `setup.py` was an explicit decision?  It would be helpful if you could add a `LICENSE.txt` or `COPYING.txt`.

If GPL is chosen, this would unfortunately (asymetrically) limit the extent to which we can share code between this and related projects such as [Kowalski](https://github.com/dmitryduev/kowalski) and [SkyPortal](https://skyportal.io).

**Comment by lpsinger** [comment]
While the two core codes that we depend on ([gwemopt](https://github.com/mcoughlin/gwemopt), [ligo.skymap](https://git.ligo.org/lscsoft/ligo.skymap)) are both GPL-licensed, this project is mostly glue code, Flask, and front-end CSS/JS, so I think that an MIT license would be entirely appropriate for us. @mcoughlin, @igorandreoni, what do you think?

**Comment by igorandreoni** [comment]
I am fine with that.

**Comment by lpsinger** [comment]
Is there an alternative to the MIT license that has the same terms but a slightly stronger language about requesting attribution of derivative works? Maybe a Creative Commons license?

**Comment by lpsinger** [comment]
Such as http://creativecommons.org/licenses/by-sa/4.0/?

**Comment by mcoughlin** [comment]
I am ok with either, I am less worried about attribution in general.

**Comment by stefanv** [comment]
If you're considering a permissive license, I would use one that is commonly applied to open source software. That would typically be MIT, modified BSD, or Apache. Users and developers already understand these.

Wrt credit, those licenses *do* require acknowledging the original authors (via reproduction of the copyright statement and license). If you add additional or more strict requirements, you risk making your license incompatible with the permissive ones.

**Comment by stefanv** [comment]
In case it is helpful, here is UC Berkeley's guidelines on software licensing: [overview](https://security.ucop.edu/resources/open-source-software-licensing.html) | [chart](https://security.ucop.edu/files/documents/resources/oss-chart.pdf).

**Comment by stefanv** [comment]
Thank you!
