### ISSUE TITLE
Ingest ICECUBE_ASTROTRACK_GOLD and ICECUBE_ASTROTRACK_BRONZE alerts

### ISSUE THREAD

**Issue by lpsinger** [growth-astro/growth-too-marshal#83]
Modify `growth.too.gcn.handle` to process `ICECUBE_ASTROTRACK_GOLD` and `ICECUBE_ASTROTRACK_BRONZE` alerts. Contact Scott Barthelmey and request an archive of past VOEvents; pick one and use it to create a unit test.

**Comment by sidmohite** [comment]
Thanks for merging @lpsinger ! I'll go ahead and close this
